import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar"
import ContactTopbar from "@/components/ContactBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col" data-new-gr-c-s-check-loaded="14.1252.0" data-gr-ext-installed="" >
        <ContactTopbar />
        <Navbar />
        <main className="flex-grow">
        {children}
        </main>
        <Footer />
      </body>
    </html>
    
  );
}
